name: single_house
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.5
  cloud_firestore: ^3.4.9
  firebase_core: ^1.23.0
  firebase_auth: ^3.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  flutter_launcher_icons: ^0.10.0

flutter_icons: 
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#FB4B4B"
  adaptive_icon_foreground: "assets/logo/logo_foreground.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
